### ISSUE TITLE
this method can work with EXPO?

### ISSUE THREAD

**Issue by karimraoudy** [fris-fruitig/react-firebase-file-uploader#12]
this method can work with EXPO?

**Comment by sprmn** [comment]
This library only works with React for the web and does not support React Native or Expo at the moment. There are a few difficulties that would make it hard to create a lib for the web like this that is compatible with RN / Expo. Difficulties include the difference between the html file input element and a native file picker, the fact that RN afaik does not support blobs, etc. I guess a separate lib for RN would make more sense. 

Feel free to try it and add submit a PR though!
