### ISSUE TITLE
unmet peer dependencies

### ISSUE THREAD

**Issue by jlibman** [fris-fruitig/react-firebase-file-uploader#14]
Trying to install, have updated firebase and react to these exact versions. Using npm version 4.1.2 - any thoughts?

`npm install -g react-firebase-file-uploader`
/usr/local/lib
├── UNMET PEER DEPENDENCY firebase@^3.5.2
├── UNMET PEER DEPENDENCY react@^15.3.2
└── react-firebase-file-uploader@2.4.1 

npm WARN react-firebase-file-uploader@2.4.1 requires a peer of firebase@^3.5.2 but none was installed.
npm WARN react-firebase-file-uploader@2.4.1 requires a peer of react@^15.3.2 but none was installed.

**Comment by sprmn** [comment]
Hi @jlibman,

Thanks for opening an issue. Is there any reason why you are installing this library globally? I wouldn't recommend that. It might have something to do with a difference between your locally and globally installed firebase/react?

**Comment by sprmn** [comment]
I'm closing this, due to inactivity.
