### ISSUE TITLE
Firebase uploader with firebase pack above 4

### ISSUE THREAD

**Issue by mikosh** [fris-fruitig/react-firebase-file-uploader#32]
I have updated the firebase pack to 5.7, unfortunatell the cool uploaded does not support it.

react-firebase-file-uploader@2.4.2 requires a peer of firebase@^3.5.2 || ^4.0.0 but none was installed.

**Comment by kitfit-dave** [comment]
You'll find that it does work anyway, we are currently using it like it is on firebase 5.5.9.

I would be nice to get an update with:
```"firebase": "^3.5.2 || ^4.0.0 || ^5.0.0"```

Also: I notice that the npm version is 2.4.2 but this repo only has tags up to 2.4.1 - did you forget to push after the npm trunk push?

Thanks
