### ISSUE TITLE
Filename formatting function issues - function takes to long time

### ISSUE THREAD

**Issue by L3n1ad** [fris-fruitig/react-firebase-file-uploader#47]
Hi,

First of all I would like to say a huge thank you for this npm it saved a lot of work for me for this project. However I run into an issue at the moment. I am using a recursive function to format the file name before upload and it seems that the function sometimes takes too long and file uploader won't wait for it so it will replace it with undefined. Would it be possible to build in a function to make sure that it will wait for the function to return a new file name before it tries to upload it? It would be very handy for me so thank you very much in advance if you can help me with that.

**Comment by alejoreact** [comment]
Hello @L3n1ad , by wating you mean you have a **async** function that resolve the filename?
or maybe your function is trying to access **this** without binding it to the component?

you can take a look [here](https://github.com/fris-fruitig/react-firebase-file-uploader/blob/a0817149ef2257a00ea49f05ba6ee89e885b0100/src/index.js#L90) to see how the filename gets handled when is a function

an example would be helpfull to see what could be happening

**Comment by L3n1ad** [comment]
hello @alejoreact, Thank you very much for you quick reply. I had a look and I realised that it was a mistake on my side I am very sorry.
