### ISSUE TITLE
Gettig error onuploadsuccess function

### ISSUE THREAD

**Issue by hkmr** [fris-fruitig/react-firebase-file-uploader#50]
```
index.js:150 Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at Observer.complete (index.js:150)
    at async.ts:27
```
```
  24 | export function async(f: Function): Function {
  25 |   return (...argsToForward: unknown[]) => {
  26 |     // eslint-disable-next-line @typescript-eslint/no-floating-promises
> 27 |     Promise.resolve().then(() => f(...argsToForward));
  28 |   };
  29 | }
```

**Comment by DavidKer1** [comment]
This problem is with firebase ^8.0.0 version, downgrade to 7.24.0 version

**Comment by jofelvi** [comment]
i have same issue

**Comment by JanaKotbrata** [comment]
I have got same issue.

**Comment by RaulNov** [comment]
Not the best solution but I changed firebase version package to firebase@7.6.1 and the error stopped happening

**Comment by iwanwmys** [comment]
Also encountering the same issue. Using firebase@8.1.1 Will downgrade for now. Thanks!

**Comment by hkmr** [comment]
It worked by downgrading the version.

**Comment by moconchobhair** [comment]
I ran into this issue as well. I don't think it should be closed.

**Comment by hkmr** [comment]
@moconchobhair Try to downgrade the firebase version. It will work fine. I know this is not a permanent solution but working right now.

**Comment by qnxdev** [comment]
var name = storageRef.child(filenameToUse).getMetadata().then(function (metadata) {
            return metadata.name;
          });

**Comment by laurensnl** [comment]
Same issue here. Is there a fix other than downgrading Firebase?

**Comment by qnxdev** [comment]
#55
