### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'name' of null

### ISSUE THREAD

**Issue by ghost** [fris-fruitig/react-firebase-file-uploader#58]
The photo is uploaded correctly.
But it shows the problem.

my code : 
```
<FirebaseFileUploder
              accept="image/*"
              name="image"
              randomizeFilename
              storageRef={firebase.storage().ref(this.props.dir)}
              onUploadStart={this.handleUploadStart}
              onUploadError={this.handleUploadError}
              onUploadSuccess={this.handleUploadSuccess}
 />
```

Error Line to your code !!  :
`return onUploadSuccess && onUploadSuccess(task.snapshot.metadata.name, task);
`

**Comment by mtcn** [comment]
check this pull request #55 

and you can use this
npm i https://github.com/qnxdev/react-firebase-file-uploader/tarball/master

Duplicate of #56

**Comment by ghost** [comment]
thanks
